sudo: false
language: php
php:
  - 7.0
  - 7.1

before_script:
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv config-rm xdebug.ini
  - phpenv rehash
  - composer install

cache:
  directories:
    - downloads
    - $HOME/.composer/cache
    - .php_cs.cache

script:
  - vendor/bin/phing phpunit phpcs php-cs-fixer-dryrun-nocache -Dphp-cs-fixer-extra-params="--using-cache=no"
