sudo: false
language: php
php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - phpenv config-rm xdebug.ini
  - phpenv rehash
  - composer install

cache:
  directories:
    - downloads
    - $HOME/.composer/cache
    - .php_cs.cache

script:
  - vendor/bin/phing phpunit phpcs php-cs-fixer-dryrun
